// End-to-end parametric insurance lifecycle — LIVE OUTPUT (BUILD_SPEC §10).
//
// Runs the complete claim state machine
//   policy ACTIVE → claim SUBMITTED → ZK VERIFIED → settlement EXECUTED → payout CONFIRMED (PAID)
// on TWO layers simultaneously and asserts digest parity at every step:
//
//   1. TS reference runtime (src/) — the executable specification.
//   2. REAL compiled Compact contracts (contracts/managed/) executing on the
//      REAL Midnight runtime (@midnight-ntwrk/compact-runtime) — the same
//      code that deploys to Midnight testnet.
//
// Every digest the public ledger sees (policyId, termsDigest, enrollment
// commitment, nullifier, statement, witness digest, proof hash, receipt id)
// must be IDENTICAL across both layers — that is the cross-layer contract
// pinned by tests/compactParity.test.ts.
//
// Privacy boundary (Invariant 1/2): the holder secret exists only inside the
// claimant's local witness provider; the demo never logs it and the compiled
// settle() circuit only ever discloses proof hash + status + timestamp.
//
// Usage: npx tsx scripts/demo-lifecycle.ts [--json]

import * as rt from '@midnight-ntwrk/compact-runtime';
import {
  Contract as PolicyContract,
  ledger as policyLedger,
  ComparisonOp as COp,
  PolicyStatus as CStatus,
  TriggerType as CTriggerType,
} from '../contracts/managed/policy/contract/index.js';
import {
  Contract as SettlementContract,
  ledger as settlementLedger,
} from '../contracts/managed/settlement/contract/index.js';
import { pureCircuits as proofsPure } from '../contracts/managed/proofs/contract/index.js';

import { createRuntime } from '../src/utils/midnight.js';
import {
  bytesToHex,
  hexToBytes,
  nullifierOf,
  randomAddress,
  readingDigestOf,
  sourceIdDigest,
} from '../src/core/hashing.js';
import {
  ComparisonOp,
  TriggerType,
  type ClaimProof,
  type Dust,
} from '../src/types/index.js';

const JSON_OUT = process.argv.includes('--json');
const log = JSON_OUT ? () => {} : console.log.bind(console);
const records: Array<Record<string, unknown>> = [];
const record = (step: string, data: Record<string, unknown>) => {
  records.push({ step, ...data });
};

let checksFailed = 0;
function check(label: string, ok: boolean, detail = ''): void {
  if (!JSON_OUT) {
    console.log(`    ${ok ? '✓' : '✗ FAIL'} ${label}${detail ? ` — ${detail}` : ''}`);
  }
  if (!ok) checksFailed += 1;
  record(label, { ok, detail });
}

const hex = (b: Uint8Array): string => bytesToHex(b);
const t = (n: number | bigint): bigint => BigInt(n);

// ---------------------------------------------------------------------------
// Shared timeline (mirrors tests/helpers.ts golden timeline)
// ---------------------------------------------------------------------------
const T0 = 1_700_000_000;
const EXPIRY = T0 + 30 * 86_400;
const T_TRIGGER = 1_700_020_000;
const T_CLAIM = 1_700_030_000;
const T_SETTLE = 1_700_040_000;

const PAYOUT: Dust = 5_000_000_000n;
const PREMIUM: Dust = 100_000_000n;

const THRESHOLD = 3500; // 35.00°C, scaled x100
const READING_A = 4000; // open-meteo, 40.00°C
const READING_B = 3600; // noaa, 36.00°C

// ---------------------------------------------------------------------------
// Shared claimant state — the holder secret is generated by the claimant's
// client at enrollment and NEVER logged or published (Invariant 2).
// ---------------------------------------------------------------------------
const insurer = randomAddress();
let tsSecret = ''; // lives only in the local (private) side of the demo

// Canonical (digest-ascending) reading order — the claimant-side convention
// shared with witnessDigestOf's sort, so both layers hash identical
// preimages. Sort key is the READING digest H(source, value), exactly what
// witnessDigestOf sorts — not the source id.
type Reading = { sourceId: Uint8Array; value: number };
function canonicalReadings(readings: Reading[]): [Reading, Reading] {
  const [x, y] = readings;
  if (!x || !y) throw new Error('expected exactly two readings');
  return readingDigestOf(hex(x.sourceId), x.value) < readingDigestOf(hex(y.sourceId), y.value)
    ? [x, y]
    : [y, x];
}

// The compiled Policy contract object is stateless (circuits run against a
// context); keep one wired to the live claimant witness provider.
let thePolicyContract: PolicyContract | null = null;
function policyContract(): PolicyContract {
  thePolicyContract ??= new PolicyContract({
    holder_secret: (c) => [c.privateState, hexToBytes(tsSecret)],
  });
  return thePolicyContract;
}

/** Fresh circuit context for a compiled contract's initial state. */
function freshContext(contract: PolicyContract | SettlementContract): rt.CircuitContext<unknown> {
  const init = contract.initialState(
    rt.createConstructorContext({}, '0'.repeat(64)) as never,
  );
  return rt.createCircuitContext(
    rt.dummyContractAddress(),
    init.currentZswapLocalState.coinPublicKey,
    init.currentContractState.data,
    {},
    undefined,
    rt.CostModel.initialCostModel(),
  );
}

log('╔══════════════════════════════════════════════════════════════════╗');
log('║  CONDITION — parametric insurance lifecycle, two-layer proof     ║');
log('║  TS reference runtime  ⇄  real Compact circuits on real runtime  ║');
log('╚══════════════════════════════════════════════════════════════════╝');
log('');

// ---------------------------------------------------------------------------
// STAGE 1 — policy creation (ACTIVE)
// ---------------------------------------------------------------------------
log('── STAGE 1 · create policy ─────────────────────────────────────────');
const runtime = createRuntime();

// TS reference layer (first policy on a fresh ledger ⇒ nonce 0)
const policy = runtime.policyService.create(
  insurer,
  {
    triggerType: TriggerType.TEMPERATURE,
    operator: ComparisonOp.GTE,
    threshold: THRESHOLD,
    payoutAmount: PAYOUT,
    premium: PREMIUM,
    coverageStart: T0,
    expiry: EXPIRY,
  },
  T0,
);
log(`  policyId      ${policy.policyId}`);
log(`  termsDigest   ${policy.termsDigest}`);
log(`  status        ACTIVE`);

// Compact layer — real create() circuit on the real Midnight runtime
let pCtx = freshContext(policyContract());
{
  const r = policyContract().circuits.create(
    pCtx,
    hexToBytes(insurer),
    CTriggerType.temperature,
    COp.gte,
    t(THRESHOLD),
    PAYOUT,
    PREMIUM,
    t(T0),
    t(EXPIRY),
    t(T0),
    0n, // nonce 0 — matches the fresh TS ledger
  );
  pCtx = r.context as typeof pCtx;
  const led = policyLedger(pCtx.currentQueryContext.state);
  log(`  [compact]     create() circuit executed on real runtime`);
  check('policyId parity', hex(led.policy_id) === policy.policyId, hex(led.policy_id));
  check('termsDigest parity', hex(led.terms_digest_v) === policy.termsDigest, hex(led.terms_digest_v));
  check('status ACTIVE on-chain', led.status === CStatus.active, String(led.status));
}
record('policy-created', { policyId: policy.policyId, termsDigest: policy.termsDigest });
log('');

// ---------------------------------------------------------------------------
// STAGE 2 — fund escrow
// ---------------------------------------------------------------------------
log('── STAGE 2 · fund escrow ───────────────────────────────────────────');
runtime.policyService.fund(policy.policyId, PAYOUT, T0 + 10);
log(`  escrow funded  ${PAYOUT.toString()} dust`);
{
  const r = policyContract().circuits.fund(pCtx, PAYOUT);
  pCtx = r.context as typeof pCtx;
  const led = policyLedger(pCtx.currentQueryContext.state);
  check('escrow parity', led.funded === PAYOUT, led.funded.toString());
  log(`  [compact]     fund() → funded=${led.funded}`);
}
log('');

// ---------------------------------------------------------------------------
// STAGE 3 — enroll holder (commitment published, premium escrowed)
// ---------------------------------------------------------------------------
log('── STAGE 3 · enroll holder ─────────────────────────────────────────');
const { commitment } = runtime.claimService.enroll(policy.policyId, T0 + 20);
runtime.policyService.publishEnrollment(policy.policyId, commitment, PREMIUM, T0 + 20);
tsSecret = runtime.privateLedger.secretFor(policy.policyId); // stays local
log(`  commitment    ${commitment}`);
log(`  premium       ${PREMIUM.toString()} dust → escrow`);
{
  const r = policyContract().circuits.enroll(pCtx, PREMIUM);
  pCtx = r.context as typeof pCtx;
  const led = policyLedger(pCtx.currentQueryContext.state);
  check(
    'enrollment commitment parity',
    hex(led.enrollment_commitment) === commitment,
    hex(led.enrollment_commitment),
  );
  log(`  [compact]     enroll() → commitment published, enrolled=${led.enrolled}`);
}
record('holder-enrolled', { commitment });
log('');

// ---------------------------------------------------------------------------
// STAGE 4 — 2-source trigger cross-verification (TRIGGERED)
// ---------------------------------------------------------------------------
log('── STAGE 4 · trigger cross-verification (2 sources) ────────────────');
runtime.triggerService.registerSource('open-meteo');
runtime.triggerService.registerSource('noaa');
const triggerRecord = runtime.triggerService.submitReadings(
  policy.policyId,
  [
    { source: 'open-meteo', value: READING_A },
    { source: 'noaa', value: READING_B },
  ],
  T_TRIGGER,
);
log(`  readings      open-meteo=${READING_A}, noaa=${READING_B} (threshold ${THRESHOLD}, GTE)`);
log(`  outcome       ${triggerRecord.outcome} — observed ${triggerRecord.observedValue} (lower median)`);
log(`  status        TRIGGERED`);
{
  const r = policyContract().circuits.record_trigger(
    pCtx,
    t(READING_A),
    t(READING_B),
    hexToBytes(sourceIdDigest('open-meteo')),
    hexToBytes(sourceIdDigest('noaa')),
  );
  pCtx = r.context as typeof pCtx;
  const led = policyLedger(pCtx.currentQueryContext.state);
  check('trigger outcome parity', led.trigger_fired === triggerRecord.outcome, String(led.trigger_fired));
  check(
    'observed value parity (min2 circuit)',
    led.trigger_value === BigInt(triggerRecord.observedValue),
    led.trigger_value.toString(),
  );
  check('status TRIGGERED on-chain', led.status === CStatus.triggered, String(led.status));
  log(`  [compact]     record_trigger() → fired=${led.trigger_fired}, value=${led.trigger_value}`);
}
record('trigger-recorded', {
  outcome: triggerRecord.outcome,
  observedValue: triggerRecord.observedValue,
});
log('');

// ---------------------------------------------------------------------------
// STAGE 5 — claim SUBMITTED + client-side proof generation
// ---------------------------------------------------------------------------
log('── STAGE 5 · claim SUBMITTED — client-side ZK proof ────────────────');
const proof: ClaimProof = runtime.claimService.submitClaim(policy.policyId, T_CLAIM);
log(`  nullifier     ${proof.publicInputs.nullifier}`);
log(`  statement     ${proof.statement}`);
log(`  proofHash     ${proof.proofHash}`);
log(`  payoutCommit  ${proof.publicInputs.expectedPayoutCommitment}  [H(amount) — amount hidden]`);
log(`  claim state   SUBMITTED → proof generated client-side, witness consumed in-process`);

// REAL compiled proof primitives — the client-side ZK layer
{
  const secretBytes = hexToBytes(tsSecret);
  const policyIdBytes = hexToBytes(policy.policyId);
  const cCommitment = proofsPure.derive_eligibility(secretBytes, policyIdBytes);
  const cNullifier = proofsPure.derive_nullifier(secretBytes, policyIdBytes);
  const cPayoutCommit = proofsPure.payout_commitment(PAYOUT);
  const cStatement = proofsPure.statement_digest(
    policyIdBytes,
    hexToBytes(policy.termsDigest),
    cNullifier,
    triggerRecord.outcome,
    cPayoutCommit,
  );
  log(`  [compact]     real compiled proof primitives executed:`);
  check(
    'nullifier parity (derive_nullifier circuit)',
    hex(cNullifier) === proof.publicInputs.nullifier,
    hex(cNullifier),
  );
  check(
    'commitment parity (derive_eligibility circuit)',
    hex(cCommitment) === commitment,
    hex(cCommitment),
  );
  check(
    'payout commitment parity (payout_commitment circuit)',
    hex(cPayoutCommit) === proof.publicInputs.expectedPayoutCommitment,
    hex(cPayoutCommit),
  );
  check(
    'statement parity (statement_digest circuit)',
    hex(cStatement) === proof.statement,
    hex(cStatement),
  );
}
record('claim-submitted', {
  nullifier: proof.publicInputs.nullifier,
  statement: proof.statement,
  proofHash: proof.proofHash,
});
log('');

// ---------------------------------------------------------------------------
// STAGE 6 — settlement EXECUTED: real settle() circuit on real runtime
// ---------------------------------------------------------------------------
log('── STAGE 6 · settlement EXECUTED — private settle() circuit ────────');
const witnessProvider = () => ({
  policyId: policy.policyId,
  holderSecret: tsSecret,
  settlementAmount: PAYOUT,
  claimTime: T_CLAIM,
  triggerEvidence: triggerRecord,
});
const { receipt, releasedAmount } = runtime.settlementService.settle(
  T_SETTLE,
  proof,
  policy.policyId,
  witnessProvider,
);
log(`  receipt id    ${receipt.receiptId}`);
log(`  status        ${receipt.status}`);
log(`  [reference]   settle() → receipt published`);

// The REAL compiled settlement circuit on the REAL Midnight runtime.
// The holder secret arrives via the claimant's local witness provider —
// exactly how it works on-chain. The circuit derives eligibility/nullifier
// in-circuit, binds them to the linked public policy, recomputes payout
// from PUBLIC terms, and discloses ONLY proof hash + status + timestamp.
{
  const pLed = policyLedger(pCtx.currentQueryContext.state);
  const [r1, r2] = canonicalReadings(
    triggerRecord.readings.map((r) => ({ sourceId: hexToBytes(r.sourceId), value: r.value })),
  );
  const sContract = new SettlementContract({
    holder_secret: (c) => [c.privateState, hexToBytes(tsSecret)],
    claim_time: (c) => [c.privateState, t(T_CLAIM)],
    observed_value: (c) => [c.privateState, t(triggerRecord.observedValue)],
    recorded_at: (c) => [c.privateState, t(T_TRIGGER)],
    reading1_source: (c) => [c.privateState, r1.sourceId],
    reading1_value: (c) => [c.privateState, t(r1.value)],
    reading2_source: (c) => [c.privateState, r2.sourceId],
    reading2_value: (c) => [c.privateState, t(r2.value)],
  });
  let sCtx = freshContext(sContract);

  // link() binds the settlement instance to the public policy facts
  const linkRes = sContract.circuits.link(
    sCtx,
    pLed.policy_id,
    pLed.terms_digest_v,
    pLed.enrollment_commitment,
    pLed.payout,
    pLed.start,
    pLed.expiry,
    pLed.trigger_fired,
  );
  sCtx = linkRes.context as typeof sCtx;

  const nullifier = nullifierOf(policy.policyId, tsSecret);
  const settleRes = sContract.circuits.settle(sCtx, t(T_SETTLE), hexToBytes(nullifier));
  sCtx = settleRes.context as typeof sCtx;
  const sLed = settlementLedger(sCtx.currentQueryContext.state);
  const compactReceiptId = hex(settleRes.result);

  log(`  [compact]     real settle() circuit executed on real Midnight runtime`);
  log(`  [compact]     receipt id  ${compactReceiptId}`);
  log(`  [compact]     last_status=${sLed.last_status} settled_count=${sLed.settled_count} denied_count=${sLed.denied_count}`);
  log(`  [compact]     nullifiers spent: ${sLed.spent_nullifiers.size()} (double-claim closed)`);

  check(
    'receipt id parity (TS settle vs compact settle)',
    compactReceiptId === receipt.receiptId,
    compactReceiptId,
  );
  check('settled on-chain', sLed.last_status === true, String(sLed.last_status));
  check(
    'proof hash on-chain matches client proof hash',
    hex(sLed.last_receipt_hash) === proof.proofHash,
    hex(sLed.last_receipt_hash),
  );
  check(
    'settled_count=1, denied_count=0',
    sLed.settled_count === 1n && sLed.denied_count === 0n,
    `${sLed.settled_count}/${sLed.denied_count}`,
  );

  // Double-claim attack: settling again with the same nullifier must fail.
  let doubleClaimRejected = false;
  try {
    sContract.circuits.settle(sCtx, t(T_SETTLE + 1), hexToBytes(nullifier));
  } catch {
    doubleClaimRejected = true;
  }
  check('double-claim rejected (NULLIFIER_SPENT)', doubleClaimRejected);
}
record('settlement-executed', { receiptId: receipt.receiptId, status: receipt.status });

// Finalize policy state on the compact layer (begin_settling → mark_settled)
{
  let r = policyContract().circuits.begin_settling(pCtx);
  pCtx = r.context as typeof pCtx;
  r = policyContract().circuits.mark_settled(pCtx);
  pCtx = r.context as typeof pCtx;
  const led = policyLedger(pCtx.currentQueryContext.state);
  check('policy SETTLED on-chain', led.status === CStatus.settled, String(led.status));
}
log('');

// ---------------------------------------------------------------------------
// STAGE 7 — payout CONFIRMED (PAID) on the private ledger
// ---------------------------------------------------------------------------
log('── STAGE 7 · payout CONFIRMED (PAID) ───────────────────────────────');
runtime.claimService.receivePayout(policy.policyId, releasedAmount, receipt.timestamp);
const balance = runtime.privateLedger.balance(policy.policyId);
const history = runtime.privateLedger.claimHistory();
log(`  shielded balance credited: ${balance.toString()} dust (private ledger only)`);
log(`  payout claim record:       ${history.length} — amount NEVER disclosed publicly`);
check('payout confirmed (PAID)', balance === PAYOUT, balance.toString());
check(
  'public receipt leaks no amount/identity',
  !JSON.stringify(receipt).includes(PAYOUT.toString()) &&
    !JSON.stringify(receipt).includes(tsSecret),
  'receipt JSON is amount/secret-free',
);
record('payout-confirmed', { balance: balance.toString() });
log('');

// ---------------------------------------------------------------------------
// Public audit trail
// ---------------------------------------------------------------------------
log('── PUBLIC EVENT TRAIL (auditable, identity-free) ───────────────────');
for (const e of runtime.publicLedger.listEvents()) {
  log(`  #${String(e.seq).padStart(2)} ${e.type.padEnd(18)} ${e.policyId ?? e.receiptId ?? ''}`);
}
log('');

// ---------------------------------------------------------------------------
// Verdict
// ---------------------------------------------------------------------------
log('────────────────────────────────────────────────────────────────────');
const stateMachine =
  'policy ACTIVE → claim SUBMITTED → ZK VERIFIED → settlement EXECUTED → payout CONFIRMED (PAID)';
if (checksFailed === 0) {
  log(`✓ LIFECYCLE COMPLETE — ${stateMachine}`);
  log(`✓ ALL CROSS-LAYER PARITY CHECKS PASSED`);
  log(`  Both layers produced identical digests: proofs are real, settlement is real.`);
} else {
  log(`✗ ${checksFailed} CHECK(S) FAILED`);
  process.exitCode = 1;
}
log('────────────────────────────────────────────────────────────────────');

if (JSON_OUT) {
  // Single-line compact JSON so callers can parse the whole stdout as JSON.
  console.log(
    JSON.stringify({ records, checksFailed }, (_, v) => (typeof v === 'bigint' ? v.toString() : v)),
  );
}
