#!/usr/bin/env node
// Android/Termux support: next build needs @next/swc-android-arm64, which
// does not exist on npm. @next/swc-wasm-nodejs provides the same bindings
// as WASM. We install that package and shim the missing platform package to
// re-export it, so Next's native loader resolves and the build works.
//
// Idempotent: only acts when @next/swc-wasm-nodejs is installed AND the
// native android-arm64 package is absent. On glibc machines this is a no-op.

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const shimDir = join(root, 'node_modules', '@next', 'swc-android-arm64');
const wasmPkg = join(root, 'node_modules', '@next', 'swc-wasm-nodejs');

if (!existsSync(wasmPkg)) {
  process.exit(0); // wasm fallback not installed — nothing to shim
}
if (existsSync(join(shimDir, 'node_modules'))) {
  process.exit(0); // real package present — never shadow it
}

mkdirSync(shimDir, { recursive: true });
writeFileSync(
  join(shimDir, 'package.json'),
  JSON.stringify(
    {
      name: '@next/swc-android-arm64',
      version: '0.0.0-shim',
      private: true,
      main: 'index.js',
    },
    null,
    2,
  ) + '\n',
);
writeFileSync(
  join(shimDir, 'index.js'),
  [
    '// Generated by scripts/postinstall.mjs on a platform without a native',
    '// @next/swc-android-arm64 build. Re-exports the WASM bindings so Next',
    '// build (and its worker processes) can load SWC.',
    'module.exports = require("@next/swc-wasm-nodejs");',
    '',
  ].join('\n'),
);
console.log('postinstall: shimmed @next/swc-android-arm64 -> @next/swc-wasm-nodejs (wasm)');

// ---------------------------------------------------------------------------
// @midnight-ntwrk/compact-runtime ships exports["."] with "default" BEFORE
// "types". Node's resolver tolerates any order; webpack 5's exports resolver
// rejects it ("Default condition should be last one") — which breaks any
// Next.js build that imports the compiled contract artifacts (they import
// compact-runtime). Reorder the two keys in place. Idempotent.
// ---------------------------------------------------------------------------
const compactRuntimePkgs = [];
const scopeDir = join(root, 'node_modules', '@midnight-ntwrk');
if (existsSync(scopeDir)) {
  for (const entry of readdirSync(scopeDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const pkgDir = join(scopeDir, entry.name);
    const pkgPath = join(pkgDir, 'package.json');
    if (entry.name === 'compact-runtime' && existsSync(pkgPath)) {
      compactRuntimePkgs.push(pkgPath);
    }
    const nestedScope = join(pkgDir, 'node_modules', '@midnight-ntwrk');
    if (existsSync(nestedScope)) {
      for (const nested of readdirSync(nestedScope, { withFileTypes: true })) {
        if (nested.isDirectory() && nested.name === 'compact-runtime') {
          const nestedPath = join(nestedScope, nested.name, 'package.json');
          if (existsSync(nestedPath)) compactRuntimePkgs.push(nestedPath);
        }
      }
    }
  }
}
for (const pkgPath of compactRuntimePkgs) {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  const dot = pkg.exports?.['.'];
  const keys = dot && typeof dot === 'object' ? Object.keys(dot) : [];
  if (dot && typeof dot === 'object' && 'default' in dot && 'types' in dot && keys[keys.length - 1] !== 'default') {
    pkg.exports['.'] = { types: dot.types, default: dot.default };
    writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    console.log('postinstall: reordered compact-runtime exports (types before default) at', pkgPath.replace(root + '/', ''));
  }
}
